### ISSUE TITLE
I encounter some problem with tearsheet.py

### ISSUE THREAD

**Issue by easytrader** [mhallsmoore/qstrader#151] opened 2016-11-19 12:27 UTC
I run the strategy.
But I encounter the problem below:
```
Traceback (most recent call last):
  File "twentydays_liquidate_rebalance1.py", line 97, in <module>
    main()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "twentydays_liquidate_rebalance1.py", line 93, in main
    run(config, testing, tickers, filename)
  File "twentydays_liquidate_rebalance1.py", line 80, in run
    results = backtest.simulate_trading(testing=testing)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/qstrader/trading_session/backtest.py", line 69, in simulate_trading
    results = self.statistics.get_results()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/qstrader/statistics/tearsheet.py", line 76, in get_results
    statistics["positions"] = self._get_positions()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/qstrader/statistics/tearsheet.py", line 109, in _get_positions
    df['avg_bot'] = df['avg_bot'].apply(x)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'avg_bot'
```

**Comment by t0m3** [comment] 2016-11-21 02:01
The issue is likely with your custom file rather than tearsheet.py

Can you share it?

**Comment by easytrader** [comment] 2016-11-21 02:35
1121 fodler includes all qstrader and twentydays_liquidate_rebalance1.py
[1121.tar.gz](https://github.com/mhallsmoore/qstrader/files/602591/1121.tar.gz)
You should type the cmd "python twentydays_liquidate_rebalance1.py --tickers=SPY,AGG > log5.txt"
for running the strategy.
I am writing the alpha 101's code for testing.

Thank you very much.

**Comment by t0m3** [comment] 2016-11-21 04:50
Have you checked your log file? Your system doesn't place trades, both your 'buy_list' and 'sell_list' are always empty

The tearsheet is erroring out due to the total lack of closed positions to output

**Comment by easytrader** [comment] 2016-11-21 06:53
Sorry, it's my mistake.
Could you add the exception or error logs for user?
That makes people easily finding their problem.

Thank you very much.

**Comment by jacohn16** [comment] 2016-12-08 05:59
I think you can hit this same error when using the BuyAndHoldStrategy().   By definition there would be no closed positions, since we're still holding the position(s) open.  I think we might want to handle this error the case where there's no closed positions, and just return an empty list.

**Comment by t0m3** [comment] 2016-12-08 09:58
The buy and hold strategy works fine as there are trades placed. The error is when no trades are placed by during the backtest

**Comment by nwillemse** [comment] 2016-12-08 14:23
I will need to fix `tearsheet` to not error out when there are no trades.

**Comment by mhallsmoore** [comment] 2016-12-12 17:13
I've just made some modifications to performance.py and tearsheet.py, primarily for the purposes of execution speed. Although I have not considered the issue here.

@nwillemse - I'm happy to fix the issue if you like?

**Comment by nwillemse** [comment] 2016-12-12 17:23
Ok thanks, sounds good @mhallsmoore

**Comment by mhallsmoore** [comment] 2017-03-15 13:22
This is now fixed.

**Closed by mhallsmoore** 2017-03-15 13:22 UTC
