### ISSUE TITLE
Import error about the code on text book "advanced algorithmic trading"

### ISSUE THREAD

**Issue by JiaMingLin** [mhallsmoore/qstrader#212] opened 2017-06-24 00:48 UTC
I tried the back tasting example given in the chapter 27, Cointegration-Based Pairs Trading using QSTrader, and the following package imports reported incorrect
```
from qstrader.strategy import Strategies, DisplayStrategy
ImportError: cannot import name Strategies
```
and
```
from qstrader.trading_session.backtest import Backtest
ImportError: No module named backtest
```
The book PDF and sample code files were created 1 February 2017.

And for my installation, I can run the example on the README successfully.

**Comment by mhallsmoore** [comment] 2017-06-29 16:27
Hi JiaMingLin,

I'm actually working on rewriting all of the code in Advanced Algorithmic Trading to make use of the latest version of QSTrader, as much has changed since February.

I am hoping to have the newest version published next week. If you check the main website (www.quantstart.com) you'll see a post up at some stage when the book has been updated.

Essentially the problem is that the ```Backtest``` module has been renamed to ```TradingSession```, along with the API for importing all of the additional modules. It was designed this way to make it far easier to run a backtest with default options, rather than having to manually specify all modules.

I'll post again here as well when it's released.

Mike.

**Comment by mhallsmoore** [comment] 2017-07-11 15:07
Hi JiaMingLin,

I've just re-released a new version of Advanced Algorithmic Trading. If you follow the link in your original download email you'll see a version for 11th July 2017. This has updated code for the latest version of QSTrader.

I'll close this issue now.

Mike.

**Closed by mhallsmoore** 2017-07-11 15:07 UTC

**Comment by femtotrader** [comment] 2017-07-11 15:17
Searching into email inbox with `subject:(QuantStart.com thank you for purchasing)` could help to find link for "Advanced Algorithmic Trading" (Last Updated: 11th July 2017) and "Successful Algorithmic Trading" (Last Updated: 18th June 2015)

@mhallsmoore ... thank you for updating AAT!

**Comment by mhallsmoore** [comment] 2017-07-11 15:23
No problem @femtotrader - Please let me know if you still have any issues with the new code and I'll fix ASAP.

**Comment by JiaMingLin** [comment] 2017-07-12 01:25
Thank you!
